name: Codacy Performance Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 6 * * 1' # Run every Monday at 6 AM

jobs:
  codacy-performance:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, dom, fileinfo, mysql, pdo_mysql, zip, gd, curl, xml, bcmath, soap, intl, readline, libxml, openssl, tokenizer, ctype, json, iconv, session, filter, hash, opcache
        coverage: xdebug
    
    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    
    - name: Performance-focused Codacy Analysis
      uses: codacy/codacy-analysis-cli-action@master
      with:
        codacy-api-token: ${{ secrets.CODACY_PROJECT_TOKEN || 'IJ2F1RZG6BfH3B7FTRdl' }}
        directory: .
        tools: phpstan,trivy
        output-format: json
        output-file: performance-codacy-results.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        comment-pr: true
        fail-build-on-issues: false
        max-issues: 500
        
    - name: Performance analysis
      run: |
        echo "Analyzing performance patterns..."
        
        # Check for N+1 queries
        echo "Checking for N+1 query problems..."
        if grep -r "->get()" --include="*.php" app/ | grep -v "vendor"; then
          echo "⚠️  Potential N+1 queries found"
        else
          echo "✅ No obvious N+1 query patterns found"
        fi
        
        # Check for inefficient loops
        echo "Checking for inefficient loops..."
        if grep -r "foreach.*foreach\|for.*for" --include="*.php" app/ | grep -v "vendor"; then
          echo "⚠️  Nested loops found"
        else
          echo "✅ No obvious nested loops found"
        fi
        
        # Check for caching opportunities
        echo "Checking for caching opportunities..."
        if grep -r "Cache::\|cache()" --include="*.php" app/ | grep -v "vendor"; then
          echo "Found caching usage in code"
        else
          echo "⚠️  No caching found - consider implementing caching"
        fi
        
        # Check for memory usage
        echo "Checking for memory usage patterns..."
        if grep -r "memory_get_usage\|memory_get_peak_usage" --include="*.php" app/ | grep -v "vendor"; then
          echo "Found memory usage monitoring"
        fi
        
    - name: Database query analysis
      run: |
        echo "Analyzing database query patterns..."
        if grep -r "DB::table\|DB::select\|DB::insert\|DB::update\|DB::delete" --include="*.php" app/ | wc -l; then
          echo "Found $(grep -r "DB::table\|DB::select\|DB::insert\|DB::update\|DB::delete" --include="*.php" app/ | wc -l) direct database queries"
        fi
        
    - name: Generate performance report
      run: |
        echo "# Codacy Performance Analysis Report" > performance-report.md
        echo "Generated on: $(date)" >> performance-report.md
        echo "" >> performance-report.md
        echo "## Performance Analysis:" >> performance-report.md
        echo "- Database query optimization" >> performance-report.md
        echo "- Loop efficiency analysis" >> performance-report.md
        echo "- Caching opportunities" >> performance-report.md
        echo "- Memory usage patterns" >> performance-report.md
        echo "- Codacy quality analysis" >> performance-report.md
        
    - name: Upload performance reports
      uses: actions/upload-artifact@v3
      with:
        name: performance-reports
        path: |
          performance-codacy-results.json
          performance-report.md
        retention-days: 30
