name: Codacy Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 2 * * 1' # Run every Monday at 2 AM

jobs:
  codacy-analysis:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Shallow clones should be disabled for better analysis
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, dom, fileinfo, mysql, pdo_mysql, zip, gd, curl, xml, bcmath, soap, intl, readline, libxml, openssl, tokenizer, ctype, json, iconv, session, filter, hash, opcache
        coverage: xdebug
    
    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    
    - name: Codacy Quality Check
      uses: codacy/codacy-analysis-cli-action@master
      with:
        # Required: Project API Token
        # Get it from: https://app.codacy.com/account/api
        # Then add it to your repository secrets as CODACY_PROJECT_TOKEN
        codacy-api-token: ${{ secrets.CODACY_PROJECT_TOKEN || 'IJ2F1RZG6BfH3B7FTRdl' }}
        
        # Optional: Directory to analyze (default: current directory)
        directory: .
        
        # Optional: Tools to run (default: all available tools)
        # tools: eslint,pmd,pylint,trivy
        
        # Optional: Fail build on issues (default: false)
        fail-build-on-issues: false
        
        # Optional: Maximum number of issues to report (default: 1000)
        max-issues: 1000
        
        # Optional: Output format (default: json)
        output-format: json
        
        # Optional: Output file
        output-file: codacy-analysis-results.json
    
    - name: Upload Codacy results
      uses: actions/upload-artifact@v3
      with:
        name: codacy-analysis-results
        path: codacy-analysis-results.json
        retention-days: 30
    
    - name: Comment PR with Codacy results
      if: github.event_name == 'pull_request'
      uses: codacy/codacy-analysis-cli-action@master
      with:
        codacy-api-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        directory: .
        output-format: json
        output-file: codacy-pr-results.json
        github-token: ${{ secrets.GITHUB_TOKEN }}
        comment-pr: true
