name: PHP Quality Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 3 * * 1' # Run every Monday at 3 AM

jobs:
  php-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, dom, fileinfo, mysql, pdo_mysql, zip, gd, curl, xml, bcmath, soap, intl, readline, libxml, openssl, tokenizer, ctype, json, iconv, session, filter, hash, opcache
        coverage: xdebug
    
    - name: Cache Composer dependencies
      uses: actions/cache@v3
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    
    - name: Run PHPStan
      run: |
        vendor/bin/phpstan analyse --memory-limit=1G --error-format=github --no-progress
        
    - name: Run PHP CodeSniffer
      run: |
        vendor/bin/phpcs --standard=PSR12 --report=checkstyle --report-file=phpcs-report.xml app/
        
    - name: Run Laravel Pint
      run: |
        vendor/bin/pint --test
        
    - name: Upload PHPCS results
      uses: actions/upload-artifact@v3
      with:
        name: phpcs-report
        path: phpcs-report.xml
        retention-days: 30
    
    - name: Comment PR with quality results
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          if (fs.existsSync('phpcs-report.xml')) {
            const report = fs.readFileSync('phpcs-report.xml', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## PHP Quality Analysis Results
              
              ### PHP CodeSniffer Report
              \`\`\`xml
              ${report}
              \`\`\`
              
              Please review and fix any issues found.`
            });
          }
